services:
  stable-diffusion-webui:
    image: rocm/pytorch:latest
    ports:
      - "80:80"
    restart: unless-stopped
    command: ["/conf/startup-comfyui.sh"]
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ipc: host
    pid: "host"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - .:/workspace
      - ./data/home:/root
      - ./data/checkpoints:/checkpoints
      - ./data/comfyui:/comfyui
      - ./conf:/conf
